### ISSUE TITLE
Multiple names timeout when working with Large collection

### ISSUE THREAD

**Issue by ErickWendel** [meirelesff/genderBR#1]
I try with 1200 items, and `get_gender`function, never stops. But when I split collection in chunks and call separatelly, works fine. Example:
``` r
for(i in 0 : length(splitted)) {
  
  d = eval(parse(text = paste('splitted', '$', '`', i, '`', sep = "")))
  for(f in d) {
    newGenders <- get_gender(f)
    if(is.na(newGenders)) {
      print(paste('Not found: ', f))
      count = count + 1
      next
    }
    
    newGenders <- gsub('Male', "Homens", newGenders)
    newGenders <- gsub('Female', "Mulheres", newGenders)
    
    print(paste(count, ' - ', f, ' - GENDER: ', newGenders))  
    genders <- c(genders, newGenders) 
    
  }
}
```

**Comment by meirelesff** [comment]
Hi, @ErickWendel, thanks for raising this issue. As the package relies on the IBGE's API, I included some pauses between requests to avoid problems. Anyway, I'm about to release an uptade that'll fix this issue.

**Comment by ErickWendel** [comment]
Nice! 

I know, the IBGE API isn't fast. But we can translate when the user pass a list to our method to an iteration and call one by one element to get_gender function.

**Comment by meirelesff** [comment]
Hi, @ErickWendel, take a look at package's new release. I guess this update fixed the issue now. Thanks for your comments.
