### ISSUE TITLE
Mapa retornando mais de 100% em um estado

### ISSUE THREAD

**Issue by ezequias** [meirelesff/genderBR#2]
Caro Fernando

Gostaria de saber como é possível um nome atingir mais de 100% na geração.

Poderia por favor testar

map_gender("rebeca", gender = "f")

Grato.
Ezequias Rocha

**Comment by meirelesff** [comment]
Dear Ezequias,

sorry for this really late response, but I'm afraid I can't help here. Checking your code and the IBGE's API, I found out that there's a problem with this first name in particular (perhaps the same happens with other first names as well). So, for the time being, the recommended thing to do is to avoid this use of map_gender. Hopefully, I'll fix these cases in future releases.

Best,
F
