### ISSUE TITLE
Problem with latin characters on MacBook

### ISSUE THREAD

**Issue by AndreFelix74** [meirelesff/genderBR#3]
get_gender("joão") returns NA when running on MacBook.
That's all information that I have now.

**Comment by AndreFelix74** [comment]
I've found out this:
https://stackoverflow.com/questions/806199/how-to-fix-weird-issue-with-iconv-on-mac-os-x

Iconv relais on system implementation
https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/iconv

> There are three main implementations of iconv in use. Linux's C runtime glibc contains one. Several platforms supply GNU libiconv, including macOS, FreeBSD and Cygwin, in some cases with additional encodings. On Windows we use a version of Yukihiro Nakadaira's win_iconv, which is based on Windows' codepages. (We have added many encoding names for compatibility with other systems.) All three have iconvlist, ignore case in encoding names and support //TRANSLIT (but with different results, and for win_iconv currently a ‘best fit’ strategy is used except for to = "ASCII").

PHP has similar warning:
https://www.php.net/manual/en/function.iconv.php

> **Caution**
> If and how //TRANSLIT works exactly depends on the system's iconv() implementation (cf. ICONV_IMPL). Some implementations are known to ignore //TRANSLIT, so the conversion is likely to fail for characters which are illegal for the out_charset

**Comment by meirelesff** [comment]
I made a few bug fixes on this code lately. Do you still face this issue?
